import { defineConfig } from "oxlint";

const config = defineConfig({
	plugins: ["unicorn"],

	rules: {
		"unicorn/catch-error-name": "warn",
		"unicorn/consistent-assert": "warn",
		"unicorn/consistent-date-clone": "warn",
		"unicorn/consistent-existence-index-check": "warn",
		"unicorn/consistent-function-scoping": [
			"warn",
			{ checkArrowFunctions: false },
		],
		"unicorn/consistent-template-literal-escape": "warn",
		"unicorn/empty-brace-spaces": "warn",
		"unicorn/error-message": "warn",
		"unicorn/escape-case": "warn",
		"unicorn/explicit-length-check": "warn",
		"unicorn/explicit-timer-delay": "warn",
		"unicorn/filename-case": "warn",
		"unicorn/import-style": "warn",
		"unicorn/max-nested-calls": "warn",
		"unicorn/no-abusive-eslint-disable": "warn",
		"unicorn/no-anonymous-default-export": "warn",
		"unicorn/no-array-reduce": "warn",
		"unicorn/no-array-reverse": "warn",
		"unicorn/no-array-sort": "warn",
		"unicorn/no-await-expression-member": "warn",
		"unicorn/no-confusing-array-with": "warn",
		"unicorn/no-console-spaces": "warn",
		"unicorn/no-document-cookie": "warn",
		"unicorn/no-empty-file": "warn",
		"unicorn/no-immediate-mutation": "warn",
		"unicorn/no-lonely-if": "warn",
		"unicorn/no-magic-array-flat-depth": "warn",
		"unicorn/no-negated-condition": "warn",
		"unicorn/no-nested-ternary": "warn",
		"unicorn/no-null": "warn",
		"unicorn/no-object-as-default-parameter": "warn",
		"unicorn/no-process-exit": "warn",
		"unicorn/no-single-promise-in-promise-methods": "warn",
		"unicorn/no-static-only-class": "warn",
		"unicorn/no-this-assignment": "warn",
		"unicorn/no-typeof-undefined": "warn",
		"unicorn/no-unnecessary-array-flat-depth": "warn",
		"unicorn/no-unnecessary-array-splice-count": "warn",
		"unicorn/no-unnecessary-await": "warn",
		"unicorn/no-unnecessary-slice-end": "warn",
		"unicorn/no-unreadable-array-destructuring": "warn",
		"unicorn/no-unreadable-iife": "warn",
		"unicorn/no-useless-collection-argument": "warn",
		"unicorn/no-useless-error-capture-stack-trace": "warn",
		"unicorn/no-useless-fallback-in-spread": "warn",
		"unicorn/no-useless-iterator-to-array": "warn",
		"unicorn/no-useless-length-check": "warn",
		"unicorn/no-useless-promise-resolve-reject": "warn",
		"unicorn/no-useless-spread": "warn",
		"unicorn/no-useless-switch-case": "warn",
		"unicorn/no-useless-undefined": [
			"warn",
			{ checkArguments: false, checkArrowFunctionBody: false },
		],
		"unicorn/no-zero-fractions": "warn",
		"unicorn/number-literal-case": "warn",
		"unicorn/numeric-separators-style": "warn",
		"unicorn/prefer-add-event-listener": "warn",
		"unicorn/prefer-array-find": "warn",
		"unicorn/prefer-array-flat": "warn",
		"unicorn/prefer-array-flat-map": "warn",
		"unicorn/prefer-array-index-of": "warn",
		"unicorn/prefer-array-some": "warn",
		"unicorn/prefer-at": "warn",
		"unicorn/prefer-bigint-literals": "warn",
		"unicorn/prefer-blob-reading-methods": "warn",
		"unicorn/prefer-class-fields": "warn",
		"unicorn/prefer-classlist-toggle": "warn",
		"unicorn/prefer-code-point": "warn",
		"unicorn/prefer-date-now": "warn",
		"unicorn/prefer-default-parameters": "warn",
		"unicorn/prefer-dom-node-append": "warn",
		"unicorn/prefer-dom-node-remove": "warn",
		"unicorn/prefer-dom-node-text-content": "warn",
		"unicorn/prefer-event-target": "warn",
		"unicorn/prefer-export-from": "warn",
		"unicorn/prefer-global-this": "warn",
		"unicorn/prefer-includes": "warn",
		"unicorn/prefer-keyboard-event-key": "warn",
		"unicorn/prefer-logical-operator-over-ternary": "warn",
		"unicorn/prefer-math-min-max": "warn",
		"unicorn/prefer-math-trunc": "warn",
		"unicorn/prefer-modern-dom-apis": "warn",
		"unicorn/prefer-modern-math-apis": "warn",
		"unicorn/prefer-module": "warn",
		"unicorn/prefer-native-coercion-functions": "warn",
		"unicorn/prefer-negative-index": "warn",
		"unicorn/prefer-node-protocol": "warn",
		"unicorn/prefer-number-coercion": "warn",
		"unicorn/prefer-number-properties": "warn",
		"unicorn/prefer-object-from-entries": "warn",
		"unicorn/prefer-optional-catch-binding": "warn",
		"unicorn/prefer-prototype-methods": "warn",
		"unicorn/prefer-query-selector": "warn",
		"unicorn/prefer-reflect-apply": "warn",
		"unicorn/prefer-regexp-test": "warn",
		"unicorn/prefer-response-static-json": "warn",
		"unicorn/prefer-set-has": "warn",
		"unicorn/prefer-set-size": "warn",
		"unicorn/prefer-single-call": "warn",
		"unicorn/prefer-spread": "warn",
		"unicorn/prefer-string-raw": "warn",
		"unicorn/prefer-string-replace-all": "warn",
		"unicorn/prefer-string-slice": "warn",
		"unicorn/prefer-string-starts-ends-with": "warn",
		"unicorn/prefer-string-trim-start-end": "warn",
		"unicorn/prefer-structured-clone": "warn",
		"unicorn/prefer-ternary": ["warn", "only-single-line"],
		"unicorn/prefer-top-level-await": "warn",
		"unicorn/prefer-type-error": "warn",
		"unicorn/relative-url-style": "warn",
		"unicorn/require-array-join-separator": "warn",
		"unicorn/require-module-attributes": "warn",
		"unicorn/require-module-specifiers": "warn",
		"unicorn/require-number-to-fixed-digits-argument": "warn",
		"unicorn/switch-case-braces": "warn",
		"unicorn/switch-case-break-position": "warn",
		"unicorn/text-encoding-identifier-case": "warn",
		"unicorn/throw-new-error": "warn",
	},
});

export default config;
