import { defineConfig } from "oxlint";

const config = defineConfig({
	rules: {
		// jest:recommended
		"jest/consistent-test-it": "off",
		"jest/expect-expect": "error",
		"jest/max-expects": "off",
		"jest/max-nested-describe": "off",
		"jest/no-alias-methods": "error",
		"jest/no-commented-out-tests": "warn",
		"jest/no-conditional-expect": "error",
		"jest/no-conditional-in-test": "off",
		"jest/no-confusing-set-timeout": "off",
		"jest/no-deprecated-functions": "error",
		"jest/no-disabled-tests": "warn",
		"jest/no-done-callback": "error",
		"jest/no-duplicate-hooks": "off",
		"jest/no-export": "error",
		"jest/no-focused-tests": "error",
		"jest/no-hooks": "off",
		"jest/no-identical-title": "error",
		"jest/no-interpolation-in-snapshots": "error",
		"jest/no-jasmine-globals": "error",
		"jest/no-large-snapshots": "off",
		"jest/no-mocks-import": "error",
		"jest/no-restricted-jest-methods": "off",
		"jest/no-restricted-matchers": "off",
		"jest/no-standalone-expect": "error",
		"jest/no-test-prefixes": "error",
		"jest/no-test-return-statement": "off",
		"jest/no-unneeded-async-expect-function": "off",
		"jest/no-untyped-mock-factory": "off",
		"jest/padding-around-after-all-blocks": "off",
		"jest/padding-around-test-blocks": "off",
		"jest/prefer-called-with": "off",
		"jest/prefer-comparison-matcher": "off",
		"jest/prefer-each": "off",
		"jest/prefer-ending-with-an-expect": "off",
		"jest/prefer-equality-matcher": "off",
		"jest/prefer-expect-assertions": "off",
		"jest/prefer-expect-resolves": "off",
		"jest/prefer-hooks-in-order": "off",
		"jest/prefer-hooks-on-top": "off",
		"jest/prefer-importing-jest-globals": "off",
		"jest/prefer-jest-mocked": "off",
		"jest/prefer-lowercase-title": "off",
		"jest/prefer-mock-promise-shorthand": "off",
		"jest/prefer-mock-return-shorthand": "off",
		"jest/prefer-snapshot-hint": "off",
		"jest/prefer-spy-on": "off",
		"jest/prefer-strict-equal": "off",
		"jest/prefer-to-be": "off",
		"jest/prefer-to-contain": "off",
		"jest/prefer-to-have-been-called": "off",
		"jest/prefer-to-have-been-called-times": "off",
		"jest/prefer-to-have-length": "off",
		"jest/prefer-todo": "off",
		"jest/require-hook": "off",
		"jest/require-to-throw-message": "off",
		"jest/require-top-level-describe": "off",
		"jest/valid-describe-callback": "error",
		"jest/valid-expect": "error",
		"jest/valid-expect-in-promise": "error",
		"jest/valid-title": "error",
	},
});

export default config;
