import { defineConfig } from "oxlint";

const config = defineConfig({
	rules: {
		// react:recommended
		// react:jsx-runtime
		// react-hooks:recommended
		// react-refresh:recommended
		"react/button-has-type": "off",
		"react/checked-requires-onchange-or-readonly": "off",
		"react/display-name": "error",
		"react/exhaustive-deps": "warn",
		"react/forbid-component-props": "off",
		"react/forbid-dom-props": "off",
		"react/forbid-elements": "off",
		"react/forward-ref-uses-ref": "off",
		"react/function-component-definition": "off",
		"react/hook-use-state": "off",
		"react/iframe-missing-sandbox": "off",
		"react/jsx-boolean-value": "off",
		"react/jsx-curly-brace-presence": "off",
		"react/jsx-filename-extension": "off",
		"react/jsx-fragments": "off",
		"react/jsx-handler-names": "off",
		"react/jsx-key": "error",
		"react/jsx-max-depth": "off",
		"react/jsx-no-comment-textnodes": "error",
		"react/jsx-no-constructed-context-values": "off",
		"react/jsx-no-duplicate-props": "error",
		"react/jsx-no-literals": "off",
		"react/jsx-no-script-url": "off",
		"react/jsx-no-target-blank": "error",
		"react/jsx-no-undef": "error",
		"react/jsx-no-useless-fragment": "off",
		"react/jsx-pascal-case": "off",
		"react/jsx-props-no-spread-multi": "off",
		"react/jsx-props-no-spreading": "off",
		"react/no-array-index-key": "off",
		"react/no-children-prop": "error",
		"react/no-danger": "off",
		"react/no-danger-with-children": "error",
		"react/no-did-mount-set-state": "off",
		"react/no-did-update-set-state": "off",
		"react/no-direct-mutation-state": "error",
		"react/no-find-dom-node": "error",
		"react/no-is-mounted": "error",
		"react/no-multi-comp": "off",
		"react/no-namespace": "off",
		"react/no-object-type-as-default-prop": "off",
		"react/no-redundant-should-component-update": "off",
		"react/no-render-return-value": "error",
		"react/no-set-state": "off",
		"react/no-string-refs": "error",
		"react/no-this-in-sfc": "off",
		"react/no-unescaped-entities": "error",
		"react/no-unknown-property": "error",
		"react/no-unsafe": "off",
		"react/no-unstable-nested-components": "off",
		"react/no-will-update-set-state": "off",
		"react/only-export-components": "error",
		"react/prefer-es6-class": "off",
		"react/prefer-function-component": "off",
		"react/react-in-jsx-scope": "off",
		"react/require-render-return": "error",
		"react/rules-of-hooks": "error",
		"react/self-closing-comp": "off",
		"react/state-in-constructor": "off",
		"react/style-prop-object": "off",
		"react/void-dom-elements-no-children": "off",

		// babel-plugin-react-compiler (undocumented. leave to default)
		// "react/capitalized-calls": "off",
		// "react/error-boundaries": "off",
		// "react/exhaustive-effect-dependencies": "off",
		// "react/globals": "off",
		// "react/hooks": "off",
		// "react/immutability": "off",
		// "react/incompatible-library": "off",
		// "react/invariant": "off",
		// "react/memo-dependencies": "off",
		// "react/no-clone-element": "off",
		// "react/no-deriving-state-in-effects": "off",
		// "react/no-react-children": "off",
		// "react/preserve-manual-memoization": "off",
		// "react/purity": "off",
		// "react/refs": "off",
		// "react/rule-suppression": "off",
		// "react/set-state-in-effect": "off",
		// "react/set-state-in-render": "off",
		// "react/static-components": "off",
		// "react/syntax": "off",
		// "react/todo": "off",
		// "react/unsupported-syntax": "off",
		// "react/use-memo": "off",
		// "react/void-use-memo": "off",
	},
});

export default config;
