import { defineConfig } from "oxlint";

const config = defineConfig({
	rules: {
		// typescript-eslint:strict-type-checked
		// typescript-eslint:stylistic-type-checked (warn)
		"typescript/adjacent-overload-signatures": "warn",
		"typescript/array-type": "warn",
		"typescript/await-thenable": "error",
		"typescript/ban-ts-comment": "error",
		"typescript/ban-tslint-comment": "warn",
		"typescript/ban-types": "off", // deprecated in v8
		"typescript/class-literal-property-style": "warn",
		"typescript/consistent-generic-constructors": "warn",
		"typescript/consistent-indexed-object-style": "warn",
		"typescript/consistent-return": "off",
		"typescript/consistent-type-assertions": "warn",
		"typescript/consistent-type-definitions": "warn",
		"typescript/consistent-type-exports": "off",
		"typescript/consistent-type-imports": "off",
		"typescript/dot-notation": "warn",
		"typescript/explicit-function-return-type": "off",
		"typescript/explicit-member-accessibility": "off",
		"typescript/explicit-module-boundary-types": "off",
		"typescript/method-signature-style": "off",
		"typescript/no-array-delete": "error",
		"typescript/no-base-to-string": "error",
		"typescript/no-confusing-non-null-assertion": "warn",
		"typescript/no-confusing-void-expression": "error",
		"typescript/no-deprecated": "error",
		"typescript/no-duplicate-enum-values": "error",
		"typescript/no-duplicate-type-constituents": "error",
		"typescript/no-dynamic-delete": "error",
		"typescript/no-empty-interface": "off", // superseeded by no-empty-object-type
		"typescript/no-empty-object-type": "error",
		"typescript/no-explicit-any": "error",
		"typescript/no-extra-non-null-assertion": "error",
		"typescript/no-extraneous-class": "error",
		"typescript/no-floating-promises": "error",
		"typescript/no-for-in-array": "error",
		"typescript/no-implied-eval": "error",
		"typescript/no-import-type-side-effects": "off",
		"typescript/no-inferrable-types": "warn",
		"typescript/no-invalid-void-type": "error",
		"typescript/no-meaningless-void-operator": "error",
		"typescript/no-misused-new": "error",
		"typescript/no-misused-promises": "error",
		"typescript/no-misused-spread": "error",
		"typescript/no-mixed-enums": "error",
		"typescript/no-namespace": "error",
		"typescript/no-non-null-asserted-nullish-coalescing": "error",
		"typescript/no-non-null-asserted-optional-chain": "error",
		"typescript/no-non-null-assertion": "error",
		"typescript/no-redundant-type-constituents": "error",
		"typescript/no-require-imports": "error",
		"typescript/no-restricted-types": "off",
		"typescript/no-this-alias": "error",
		"typescript/no-unnecessary-boolean-literal-compare": "error",
		"typescript/no-unnecessary-condition": "error",
		"typescript/no-unnecessary-parameter-property-assignment": "off",
		"typescript/no-unnecessary-qualifier": "off",
		"typescript/no-unnecessary-template-expression": "error",
		"typescript/no-unnecessary-type-arguments": "error",
		"typescript/no-unnecessary-type-assertion": "error",
		"typescript/no-unnecessary-type-constraint": "error",
		"typescript/no-unnecessary-type-conversion": "error",
		"typescript/no-unnecessary-type-parameters": "error",
		"typescript/no-unsafe-argument": "error",
		"typescript/no-unsafe-assignment": "error",
		"typescript/no-unsafe-call": "error",
		"typescript/no-unsafe-declaration-merging": "error",
		"typescript/no-unsafe-enum-comparison": "error",
		"typescript/no-unsafe-function-type": "error",
		"typescript/no-unsafe-member-access": "error",
		"typescript/no-unsafe-return": "error",
		"typescript/no-unsafe-type-assertion": "off",
		"typescript/no-unsafe-unary-minus": "error",
		"typescript/no-useless-default-assignment": "error",
		"typescript/no-useless-empty-export": "off",
		"typescript/no-var-requires": "off", // superseeded by no-require-imports
		"typescript/no-wrapper-object-types": "error",
		"typescript/non-nullable-type-assertion-style": "warn",
		"typescript/only-throw-error": "error",
		"typescript/parameter-properties": "off",
		"typescript/prefer-as-const": "error",
		"typescript/prefer-enum-initializers": "off",
		"typescript/prefer-find": "warn",
		"typescript/prefer-for-of": "warn",
		"typescript/prefer-function-type": "warn",
		"typescript/prefer-includes": "warn",
		"typescript/prefer-literal-enum-member": "error",
		"typescript/prefer-namespace-keyword": "error",
		"typescript/prefer-nullish-coalescing": "warn",
		"typescript/prefer-optional-chain": "warn",
		"typescript/prefer-promise-reject-errors": "error",
		"typescript/prefer-readonly": "off",
		"typescript/prefer-readonly-parameter-types": "off",
		"typescript/prefer-reduce-type-parameter": "error",
		"typescript/prefer-regexp-exec": "warn",
		"typescript/prefer-return-this-type": "error",
		"typescript/prefer-string-starts-ends-with": "warn",
		"typescript/prefer-ts-expect-error": "off", // superseeded by ban-ts-comment
		"typescript/promise-function-async": "off",
		"typescript/related-getter-setter-pairs": "error",
		"typescript/require-array-sort-compare": "off",
		"typescript/require-await": "error",
		"typescript/restrict-plus-operands": "error",
		"typescript/restrict-template-expressions": "error",
		"typescript/return-await": "error",
		"typescript/strict-boolean-expressions": "off",
		"typescript/strict-void-return": "off",
		"typescript/switch-exhaustiveness-check": "off",
		"typescript/triple-slash-reference": "error",
		"typescript/unbound-method": "error",
		"typescript/unified-signatures": "error",
		"typescript/use-unknown-in-catch-callback-variable": "error",
	},
});

export default config;
