name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install -g husky # workaround
      - run: bun install --frozen-lockfile

      - run: bunx npm pack
      - uses: actions/upload-artifact@v7
        with:
          path: kekkon-nexus-config-*.tgz
