name: CI

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - "**"

jobs:
  qc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: oven-sh/setup-bun@v2
      - run: bun ci

      - run: bun run prepack
      - run: bun run --cwd packages/create prepack

      - run: bun vp check
      - run: bun run test

      - run: bun run pack

      - uses: actions/upload-artifact@v7
        with:
          name: config
          path: kekkon-nexus-config-*.tgz
          archive: false
      - uses: actions/upload-artifact@v7
        with:
          name: create-config
          path: kekkon-nexus-create-config-*.tgz
          archive: false
