name: CI

on:
  workflow_dispatch:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2
      - run: bun ci

      - run: bun run prepack
      - run: bun run --cwd packages/create prepack

      - run: bun vp check
      - run: bun run test

      - run: bun run pack

      - uses: actions/upload-artifact@v7
        with:
          name: config
          path: kekkon-nexus-config-*.tgz
          archive: false
      - uses: actions/upload-artifact@v7
        with:
          name: create-config
          path: kekkon-nexus-create-config-*.tgz
          archive: false

  cd:
    needs: [ci]
    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      id-token: write
      attestations: write
      artifact-metadata: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v8
        with:
          merge-multiple: true
      - uses: actions/attest@v4
        with:
          subject-path: "*"

      - run: npm install -g npm@latest
      - run: for pkg in *; do npm publish "$pkg"; done
